#cloud-config
users:
  - name: sym
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8BLM9LJVAdGFQYUeMvZ56Ll3sWUoPp3p+1zvIaqg73tn470fTgiQ6MOS/cKjbZqcN242H1Ih+oUDAkbMky2ks/9HaxAgxHsYoRBcSmeafq6x0JLhom72j5LC2zChMeyGLpt/6OfacPPL8PdZsW9V/sCzSQUD7AIc+/bgqpTIn/XfpTTMNUZi8qkoDMr53TgZhq70p5ZZp2z0IUSgkZ5LELxlOkhTRwA6ShYd1EWFsvLddze2vQUCZfSWecVoVejBRJ6jaOTecP866XSciQu6poab0brFCm3k0377UMljXYWCqs653xgK1xyrO2ezhicyKxszh77qfIrTMQdGL+wYz symroe@Syms-MacBook-Pro.local"
  - name: chris
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDP700VjbnTIwRnOemtcJJGPr0Pgq8gOwhR4SVBR/50RVGddX7Jw9XqW8wMNmI93xZPV5YR5JfMlnvaMfAgHD1zdSBPs1lbx8MZahbVgBQTirLaHorjglzUXTBzLnnopC8DVt4IwFuh3vR71+rVn3vum8/fJAI7ISdBdkcDxHkv4zIa3I+sQ22YmflnzpJA/l1A7WJYTQUjLiDElijWHHwMQv86SBpxsHN3u3nEyaylrINDI3L4FTTnBWX+fF/Hxaobn98xiCas8Ho8Ecmvy/ZbP+GS7fJeKZmQCm0ROSCJ1LdAAydprAfYwMG8vPnut3fO7/8MxyT0PbYiiG4I9z7P chris@leonard"

runcmd:
  - "/var/www/every_election/env/bin/python /var/www/every_election/code/manage.py dumpdata elections election_snooper --indent 4 -o /var/www/every_election/code/every_election/data/elections.json"
  - "chown every_election:every_election /var/www/every_election/code/every_election/data/elections.json"
{% if aws_env == 'test' %}
  - "/etc/init.d/cron stop"
{% endif %}
